### ISSUE TITLE
kosko4 + subdomain

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kosko-charts#316]
Looks like the `config.subdomain` is not active anymore.

The prod snapshot here should create the ingress with that subdomain but it doesnt : https://github.com/SocialGouv/archifiltre-site/pull/112

**Comment by revolunet** [comment]
A priori c'est dû au merge ici, sur lequel gitlab override la config user 

https://github.com/SocialGouv/kosko-charts/blob/alpha/src/components/app/index.ts#L69

**Comment by douglasduteil** [comment]
🤔 it's overridden by `gitlab(process.env)` ?

**Comment by douglasduteil** [comment]
We should write a test case to ensure this

**Comment by revolunet** [comment]
yes; ive added a snapshot in #317

**Comment by revolunet** [comment]
fixed in upcoming v4
